In [21]:
# getting dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

# 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

--2024-11-25 19:39:15--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  1.83MB/s    in 0.6s    

2024-11-25 19:39:16 (1.83 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [22]:
# reading file
with open("input.txt", 'r', encoding='utf-8') as file:
    full_text = file.read()
print(len(full_text))
print(full_text[:100])

1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [23]:
characters = sorted(set(full_text))
VOCAB_SIZE = len(characters)
print(characters)
print(VOCAB_SIZE)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
65


In [24]:
# look into tiktoken

# character-to-index mapping
def create_mapping():
    mapping = {}
    for i, ch in enumerate(characters):
        mapping[ch] = i
    return mapping

# encode a string using the mapping
def encode(string, mapping):
    encoded = []
    for c in string:
        encoded.append(mapping[c])
    return encoded

# reverse mapping for decoding
def create_reverse_mapping(mapping):
    reverse_mapping = {}
    for ch, i in mapping.items():
        reverse_mapping[i] = ch
    return reverse_mapping

# decode an encoded list back to the original string
def decode(encoded, reverse_mapping):
    decoded = []
    for i in encoded:
        decoded.append(reverse_mapping[i])
    return ''.join(decoded)

encoder_map = create_mapping()
decoder_map = create_reverse_mapping(encoder_map)

sample_string = encode("hola", encoder_map)
print("Encoded:", sample_string)

decoded_string = decode(sample_string, decoder_map)
print("Decoded:", decoded_string)


Encoded: [46, 53, 50, 39]
Decoded: hola


In [25]:
import torch

torch.manual_seed(1)
data = torch.tensor(encode(full_text, encoder_map), dtype=torch.int64) # convert data into a tensor
print(data[:100])

split = int(0.8*len(data))
training_set = data[:split] # split into training and validation set
validation_set = data[split:]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [26]:
context_size = 16 # the batch size to contain context in
batch_size = 8 # how many sequences we are processing in each epoch

x = training_set[:context_size]
y = training_set[1:context_size+1] # y is the character after x

In [27]:
def get_batch(split): # generate a small batch of data to process of inputs x and targets y

    if split == 'train':
        data = training_set
    else:
        data =  validation_set

    # generate a random starting point and generate a batch from that
    random_batch = torch.randint(len(data) - context_size, (batch_size,))
    x = torch.stack([data[i:i+context_size] for i in random_batch])
    y = torch.stack([data[i+1:i+context_size+1] for i in random_batch])

    return x, y

x_sample, y_sample = get_batch('train')
print(x_sample)
print(y_sample)
print(x_sample.shape)

tensor([[ 1, 47, 58,  1, 58, 53,  1, 39,  1, 46, 39, 54, 54, 63,  1, 47],
        [57,  1, 55, 59, 43, 43, 52,  6,  1, 54, 39, 56, 58,  1, 53, 44],
        [61, 43, 58,  1, 58, 46, 43, 47, 56,  1, 41, 46, 43, 43, 49, 57],
        [50,  1, 46, 47, 51,  6,  1, 47, 52,  1, 46, 53, 54, 43,  1, 46],
        [20, 43, 56, 43,  1, 41, 53, 51, 43, 57,  1, 30, 53, 51, 43, 53],
        [63, 53, 59,  1, 52, 53, 61, 12,  0,  0, 35, 13, 30, 35, 21, 15],
        [53, 44,  1, 58, 46, 43, 57, 43,  1, 51, 53, 39, 52, 57,  2,  0],
        [ 1, 40, 43, 39, 56,  1, 47, 58,  1, 39, 57,  1, 63, 53, 59,  1]])
tensor([[47, 58,  1, 58, 53,  1, 39,  1, 46, 39, 54, 54, 63,  1, 47, 57],
        [ 1, 55, 59, 43, 43, 52,  6,  1, 54, 39, 56, 58,  1, 53, 44,  1],
        [43, 58,  1, 58, 46, 43, 47, 56,  1, 41, 46, 43, 43, 49, 57,  0],
        [ 1, 46, 47, 51,  6,  1, 47, 52,  1, 46, 53, 54, 43,  1, 46, 43],
        [43, 56, 43,  1, 41, 53, 51, 43, 57,  1, 30, 53, 51, 43, 53,  6],
        [53, 59,  1, 52, 53, 61, 12, 

In [ ]:
import torch.nn as nn
from torch.nn import functional

class BigramModel(nn.Module):

    def __init__(self, vocabulary_size):
        super().__init__()
        self.embedding_table = nn.Embedding(vocabulary_size, vocabulary_size) # we create a 65 x 65 embedding table
        self.loss_fn = nn.CrossEntropyLoss()

    def forward(self, index, targets):
        logits = self.embedding_table(index) # logits are used to convert into a probability distribution for each token prediction
        logits = logits.view(-1, logits.size(-1))
        targets = targets.view(-1) # logits and targets must be resized to be used with NNs
        loss = self.loss_fn(logits, targets) # calculate difference between predicted value and target value

        return logits, loss

sample_model = BigramModel(VOCAB_SIZE)
sample_logits, sample_loss = sample_model(x_sample, y_sample)

print(sample_logits.shape, sample_loss)

torch.Size([128, 65]) tensor(4.5000, grad_fn=<NllLossBackward0>)
